services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'lampserver'
      MYSQL_USER: lampserver
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    networks:
      - lamp-docker
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    image: php:apache
    volumes:
      - './:/var/www/html'
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
